[build]
  base = "client"
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_URL = "https://whass-api.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 