branch-defaults:
  main:
    environment: whass-backend-prod
    group_suffix: null
global:
  application_name: whass-hosting
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js 18
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  repository: null
  sc: git
  workspace_type: Application 