version: '3.8'

services:
  # Servicio de base de datos MongoDB
  mongo:
    image: mongo:6-jammy
    container_name: whass-mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - whass-network

  # Servicio de backend
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: whass-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/whass-hosting
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=30d
      - JWT_COOKIE_EXPIRE=30
    depends_on:
      - mongo
    networks:
      - whass-network

  # Servicio de frontend
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: whass-frontend
    restart: always
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:5000/api
    depends_on:
      - backend
    networks:
      - whass-network

# Definición de volúmenes
volumes:
  mongo-data:
    driver: local

# Definición de redes
networks:
  whass-network:
    driver: bridge 