services:
  # Backend API service
  - type: web
    name: whass-backend
    env: node
    rootDir: server
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_EXPIRE
        value: 30d
      - key: JWT_COOKIE_EXPIRE
        value: 30
      - key: JWT_SECRET
        value: whass_xHlmDHxypDVWOv2Cu8fY7FgCw1JZXEgXkIGC2JjGDmh6yJ08
      # Nota: Deberás agregar manualmente la URL de MongoDB Atlas
      - key: MONGO_URI
        value: mongodb+srv://davdlasso:ddslasso14@cluster0.9lewey2.mongodb.net/whass?retryWrites=true&w=majority&appName=Cluster0
    autoDeploy: true

  # Frontend service como web site en lugar de static
  - type: web
    name: whass-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    envVars:
      - key: VITE_API_URL
        value: https://whass-backend.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
