services:
  # Backend API service
  - type: web
    name: whass-backend
    env: node
    rootDir: server
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_EXPIRE
        value: 30d
      - key: JWT_COOKIE_EXPIRE
        value: 30
      - key: JWT_SECRET
        value: whass_xHlmDHxypDVWOv2Cu8fY7FgCw1JZXEgXkIGC2JjGDmh6yJ08
      # Nota: Deberás agregar manualmente la URL de MongoDB Atlas
      - key: MONGO_URI
        sync: false
    autoDeploy: true

  # Frontend service
  - type: static
    name: whass-frontend
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://whass-backend.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
