services:
  # Backend API service
  - type: web
    name: whass-backend
    env: node
    rootDir: server
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_EXPIRE
        value: 30d
      - key: JWT_COOKIE_EXPIRE
        value: 30
      - key: JWT_SECRET
        value: whass_xHlmDHxypDVWOv2Cu8fY7FgCw1JZXEgXkIGC2JjGDmh6yJ08
      - key: MONGO_URI
        value: mongodb://whass_admin:Whass_MongoDB_4226@whass-mongodb:27017/whass?authSource=admin
    autoDeploy: true

  # MongoDB database
  - type: pserv
    name: whass-mongodb
    env: docker
    repo: https://github.com/render-examples/mongodb.git
    envVars:
      - key: MONGO_INITDB_ROOT_USERNAME
        value: whass_admin
      - key: MONGO_INITDB_ROOT_PASSWORD
        value: Whass_MongoDB_4226
    disk:
      name: data
      mountPath: /data/db
      sizeGB: 1
      
  # Frontend service
  - type: web
    name: whass-frontend
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://whass-backend.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
