services:
  # Backend API service
  - type: web
    name: whass-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_EXPIRE
        value: 30d
      - key: JWT_COOKIE_EXPIRE
        value: 30
      - key: JWT_SECRET
        sync: false
      - key: MONGO_URI
        sync: false
    autoDeploy: true

  # MongoDB database
  - type: pserv
    name: whass-mongodb
    env: docker
    repo: https://github.com/render-examples/mongodb.git
    envVars:
      - key: MONGO_INITDB_ROOT_USERNAME
        sync: false
      - key: MONGO_INITDB_ROOT_PASSWORD
        sync: false
    disk:
      name: data
      mountPath: /data/db
      sizeGB: 1 